### ISSUE TITLE
Crash with un-bodied audience

### ISSUE THREAD

**Issue by tenuki** [facundobatista/typuspocus#4]
```
(env) aweil@T460p:/tmp/typuspocus$ python -m typuspocus
pygame 2.6.1 (SDL 2.28.4, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
WARNING: couldn't load hi scores file from '/home/aweil/.local/share/typuspocus/hiscores'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/typuspocus/typuspocus/__main__.py", line 2, in <module>
    game.main()
  File "/tmp/typuspocus/typuspocus/game.py", line 1301, in main
    g.run(MainMenu(g))
  File "/tmp/typuspocus/typuspocus/engine.py", line 31, in run
    scene.run()
  File "/tmp/typuspocus/typuspocus/engine.py", line 89, in run
    self.event(event)
  File "/tmp/typuspocus/typuspocus/game.py", line 1197, in event
    self.do_action(sel)
  File "/tmp/typuspocus/typuspocus/game.py", line 1202, in do_action
    self.play_history()
  File "/tmp/typuspocus/typuspocus/game.py", line 1234, in play_history
    laAudiencia = audiencia.Audiencia(count, wardrobes)
  File "/tmp/typuspocus/typuspocus/audiencia.py", line 287, in __init__
    self.engine = IntroEngine(self.personas, level_number, wardrobe)
  File "/tmp/typuspocus/typuspocus/audiencia.py", line 145, in __init__
    p = Persona(inicial, level_number, wardrobe)
  File "/tmp/typuspocus/typuspocus/audiencia.py", line 30, in __init__
    individuo = people.buildIndividual(level_number, wardrobe)
  File "/tmp/typuspocus/typuspocus/people.py", line 478, in buildIndividual
    i.random(level=level + 1, clothinBehavior=wd.behaviourname)
  File "/tmp/typuspocus/typuspocus/people.py", line 214, in random
    sl.remove('body')
AttributeError: 'dict_keys' object has no attribute 'remove'
```

Code:

```
class Individual:

    def __init__(self, wardrobe):
        """Each person must have a wardrobe, Ha!"""
        self.wardrobe = wardrobe
        self.layers = {}

    def random(self, level=1, clothinBehavior="anypublic"):
        # let's get the clothing behaviour
        clothinBehavior = BehaviourDatas[clothinBehavior]

        # choose some layers by it's probe
        sl = []
        for layer in self.wardrobe.getLayers():
            if random.random() < clothinBehavior[layer]:
                sl.append(layer)

        # if this individual is not going to have a body
        # at least let him be well clothed, for its health!
        if 'body' not in sl:
            sl = clothinBehavior.keys()
            sl.remove('body')

        # let's wardrobe calculate weights for this level
        self.wardrobe.adjustProbForLevel(level)

        # choose clothes, please!!
        for layer in sl:
            if layer not in self.wardrobe.articles:
                continue
            r = random.random()
            s = 0
            for art in self.wardrobe.articles[layer]:
                s += art.absProb(level)
                if r < s or s == 1:
                    self.layers[layer] = art
                    break
```

In the case of the bug this code is executed:
```
        # if this individual is not going to have a body
        # at least let him be well clothed, for its health!
        if 'body' not in sl:
            sl = clothinBehavior.keys()
            sl.remove('body')
```

and is strange that randomization above this code is ignored when doing this: ` sl = clothinBehavior.keys()` ..

**Comment by facundobatista** [comment]
Fixed in #5
